skin: "/assets/css/skins/default.css"
locale: en-US
title: "nonomino"
description: "This site may or may not guide you to life, the universe and everything."
baseurl:
url: "https://nonomino.is-a.dev"
logo: /images/avatar.jpg
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable:
  combo:
  tags:
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Comfortaa"
    weights: "400,400i,700,700i"
google_analytics: 
disqus:
  shortname: 
twitter:
  username: "nonominox"

liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

search_full_content: false 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

author:
  name: nonomino
  picture: /images/avatar.jpg
  email: nonomino@perso.be
  twitter: nonominox
  links:
    - title:
      url:
      icon:

footer_links:
  - title: email
    url: mailto:nonomino@perso.be
    icon: fas fa-envelope
  - title: Linkedin
    url: https://likedin.com/in/nonominos
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/nonomino
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square